allow @ in identifiers
Identifiers can contain the @ symbol, a typical example is
```
put @resources << /ColorSpace @pgfcolorspaces >>
```
as found in documents created with LaTeX package pgf and colorspaces.

At the moment a pdf containing the above will trigger an error:
```
pdfminer.psparser.PSSyntaxError: Invalid dictionary construct: [/'ColorSpace', /b'@', /b'pgfcolorspaces']
```
since @ is parsed as separate token.